# Generated by Django 3.2 on 2023-02-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employees_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
